before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: kXh+9kC+VE7p1AYjFs/gPA0Q+HAYYLxDLt4YnnkXgZ8Owm/aSEo4IFu0C8byO97s38TgsDO1NrUyJOTKhSxSsGt8uXfpjNBSW8C7SUo/HuHrTnRi6zyxIeIuwKFQVw1pVzh+oLew8+kxu2IPI6If54sRlGSSczLWUx/+XXRgX/mFntgNgURx2z6/GziP+05z/v0wh5VvAL22VItzAkhL68hL68CgPWleeo9d0wMdKvvCZiJGw8Nwzo+gdUISTtczdsZWsypmr+QTo0lKGH66luCMykfYr4vPJ1J8GMT/6fni/T8i7d8UBoJ5TbCA7SBZ/f9PFxPT7mqtihPZFIyGTlQAQBq2ba4K3++XAobVnnSootcInuvjaFM8fKmIcnS6xK7vDOyhht4YMAbP7/cytCuYfxu+IMbe0NfElew3cfMtWws00FWEITc5kWq31EunLGhCQgiglproa7NPokMfbU88kTteibBeba8huYPiqnrR0ST35Z2OWk0StDxWPpOo9Sy8D2kM/4PSLNebkVT+koz4fELqLKSXaLF70en4hLVbAgsft75f2BElo7iGM8uetteaMtljzRMIhJJEIK0f75reVDA34PsqnL4iO4/rvbcHXBdsrbsw6TTGrIP2P0RMZI+I0CQrqR2Dpy/rKPh2Xb12qnz/7XuNGkdZ+h4pLsU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
